INSERT INTO `links` 
(`link_id`, `link_function`,  `link_name`, `link_url`, `link_open`, `link_class`, `link_owner`, `link_category`,  `link_order` ) 
VALUES 
(1, 'efiction::home', 'LAN_EFICTION_HOME', 'index.php', '0',  0, 'efiction', '1', 1),
(2, 'efiction::recent', '_MOSTRECENT', 'browse.php?type=recent', '0', 0, 'efiction', '1', 2),
(3, 'efiction::login', '_LOGIN', 'login.php', '0', 0, 'efiction', '2', 3),
(4, 'efiction::adminarea', 'LAN_EFICTION_ADMINAREA', 'admin.php', '0', 254, 'efiction', '2', 4),
(5, 'efiction::logout', 'LAN_EFICTION_LOGOUT', 'index.php?logout', '0', 253, 'efiction', '2', 5),
(6, 'efiction::featured', 'LAN_EFICTION_FEATURED', 'browse.php?type=featured', '0', 0, 'efiction', '1', 6),
(7, 'efiction::catslink', '_CATEGORIES', 'browse.php?type=categories', '0', 0, 'efiction', '1', 7),
(8, 'efiction::members', '_MEMBERS', 'authors.php?action=list', '0', 0, 'efiction', '1', 8),
(9, 'efiction::authors', '_AUTHORS', 'authors.php?list=authors', '0', 255, 'efiction', '1', 9),
(10, 'efiction::help', 'LAN_HELP', 'viewpage.php?page=help', '0', 0, 'efiction', '4', 10),
(11, 'efiction::search', '_SEARCH', 'searching.php', '0', 0, 'efiction', '1', 11),
(12, 'efiction::series', '_SERIES', 'browse.php?type=series', '0', 0, 'efiction', '1', 12),
(13, 'efiction::tens', 'LAN_EFICTION_TENS', 'toplists.php', '0', 0, 'efiction', '1', 13),
(14, 'efiction::challenges', 'LAN_EFICTION_CHALLENGES', 'browse.php?type=challenges', '0', 0, 'efiction', '1', 14),
(15, 'efiction::contactus', '_CONTACTUS', 'contact.php', '0', 0, 'efiction', '1', 15),
(16, 'efiction::rules', 'LAN_EFICTION_RULES', 'viewpage.php?page=rules', '0', 0, 'efiction', '4', 16),
(17, 'efiction::tos', 'LAN_EFICTION_TOS', 'viewpage.php?page=tos', '0', 0, 'efiction', '4', 17),
(18, 'efiction::rss', 'LAN_EFICTION_RSS', 'rss.php', '0', 0, 'efiction', '1', 18),
(19, 'efiction::member', 'LAN_EFICTION_ACCOUNT', 'member.php', '0', 1, 'efiction', '2', 19),
(20, 'efiction::titles', '_TITLES', 'browse.php?type=titles', '0', 0, 'efiction', '1', 20),
(21, 'efiction::register', '_REGISTER', 'signup.php', '0', 0, 'efiction', '2', 21),
(22, 'efiction::lostpassword', '_LOSTPASSWORD', 'fpw.php', '0', 0, 'efiction', '2', 22),
(23, 'efiction::newsarchive', 'LAN_EFICTION_NEWS', 'news.php', '0', 0, 'efiction', '1', 23),
(24, 'efiction::browse', '_BROWSE', 'browse.php', '0', 0, 'efiction', '1', 24),
(25, 'efiction::charslink', '_CHARACTERS', 'browse.php?type=characters', '0', 0, 'efiction', '1', 25),
(26, 'efiction::ratings', '_RATINGS', 'browse.php?type=ratings', '0', 0, 'efiction', '1', 26);

